name: Docker Build and Push

on:
  push:
    branches: [ main ]

# PERMISOS NECESARIOS
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Login en GitHub Container Registry usando el token del sistema
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Login en Azure ACR (Asegúrate de tener estos secrets en GitHub)
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Build y Tag (Cambiado a 'frontend' para ser exactos)
      - name: Build and Tag
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/frontend:latest \
                         -t ${{ secrets.ACR_NAME }}.azurecr.io/multiscrapper-frontend:latest

      # 4. Push a ambos registros
      - name: Push Images
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/multiscrapper-frontend:latest
